spring:
  application:
    name: springboot-batch
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yourdatabase
    username: yourname
    password: yourpass
